import fs from 'fs';
const [,,port,url,out,sel,w] = process.argv;
const list = await (await fetch(`http://127.0.0.1:${port}/json/list`)).json();
const t = list.find(x=>x.type==='page');
const ws = new WebSocket(t.webSocketDebuggerUrl);
let id=0; const p={};
ws.onmessage=(e)=>{const d=JSON.parse(e.data);if(d.id&&p[d.id]){p[d.id](d.result||d.error);delete p[d.id];}};
const send=(m,params={})=>new Promise(r=>{const i=++id;p[i]=r;ws.send(JSON.stringify({id:i,method:m,params}));});
await new Promise(r=>{ws.onopen=r;});
await send('Page.enable');
await send('Emulation.setDeviceMetricsOverride',{width:+w,height:900,deviceScaleFactor:2,mobile:false});
await send('Page.navigate',{url});
await new Promise(r=>setTimeout(r,2000));
const r0 = await send('Runtime.evaluate',{expression:`(()=>{const e=document.querySelector('${sel}');e.scrollIntoView({block:'center'});return 1})()`});
await new Promise(r=>setTimeout(r,2200));
const r1 = await send('Runtime.evaluate',{expression:`(()=>{const e=document.querySelector('${sel}');const b=e.getBoundingClientRect();return JSON.stringify({x:Math.round(b.x)-24,y:Math.round(b.y)-24,w:Math.round(b.width)+48,h:Math.round(b.height)+48})})()`,returnByValue:true});
const c = JSON.parse(r1.result.value);
const r = await send('Page.captureScreenshot',{format:'png',clip:{x:c.x,y:c.y,width:c.w,height:c.h,scale:2}});
fs.writeFileSync(out, Buffer.from(r.data,'base64'));
ws.close();
